version: "3.8"

services:
    api:
        build:
            context: .
        ports:
            - "80:80"
        depends_on:
            - mongodb
        volumes:
            - ./app:/app
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
volumes:
    mongo_data: